#
# Quarkus
#
quarkus:
  console:
    color: true
  datasource:
    jdbc:
      url: "jdbc:h2:tcp://localhost/C:/Daten/h2/test"
      transactions: xa
    username: sa
  log:
    category:
      "com.arjuna":
        level: info
      "de.quoss.example.camel.quarkus.xa.fromjms.todb.CustomTracer":
        level: info
      "de.quoss.example.camel.quarkus.xa.fromjms.todb.CustomTransactionHelper":
        level: info
      "de.quoss.example.camel.quarkus.xa.fromjms.todb.MainRoute":
        level: info
    console:
      color: true
      enable: false
    file:
      enable: true
      format: "%d [%t] [%X] %p %c %m%n"
    level: info
    min-level: trace

#
# Camel
#
camel:
  main:
    message-history: true
    tracing: true
    use-breadcrumb: true
    use-mdc-logging: true
