#
# Quarkus
#
quarkus:
  artemis:
    url: tcp://localhost:61616
  datasource:
    jdbc:
      url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
      transactions: xa
    username: sa
  log:
    # category:
      # "com.arjuna":
        # level: trace
      # "de.quoss.example.camel.quarkus.xa.fromjms.todb.CustomTracer":
        # level: trace
    console:
      enable: false
    file:
      enable: true
      format: "%d [%t] [%X] %p %c %m%n"
      path: target/test.log
    level: info
    min-level: trace

#
# Camel
#
camel:
  main:
    message-history: false
    tracing: false
    use-breadcrumb: true
    use-mdc-logging: true
